export const fileTypes: string[] = [
  "application/msword",
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  "image/jpg",
  "image/jpeg",
  "image/png",
  "image/gif",
  "application/zip",
  "application/x-rar-compressed",
  "application/pdf",
  "video/mp4",
  "audio/mpeg",
  "video/quicktime",
  "video/x-msvideo",
  "video/x-matroska",
  "application/vnd.openxmlformats-officedocument.presentationml.presentation",
  "application/vnd.ms-excel",
];
